stages:
  load_data:
    cmd: python src/load_data.py --config=params.yaml
    deps: 
    - src/get_data.py
    - src/load_data.py
    - source_code/Titanic_survival.csv
    
    outs:
    - data/raw/Titanic_survival.csv
  
  split_data:
    cmd: python src/split_data.py --config=params.yaml
    deps:
    - src/split_data.py
    - data/raw/Titanic_survival.csv

    outs:
    - data/processed/test_titanic_survival.csv
    - data/processed/train_titanic_survival.csv

  train_and_evaluate:
    cmd: python src/train_and_evaluate.py --config=params.yaml
    deps:
    - data/processed/test_titanic_survival.csv
    - data/processed/train_titanic_survival.csv
    - src/train_and_evaluate.py

    params:
    - estimators.XGBClassifier.params.booster
    - estimators.XGBClassifier.params.max_depth
    
    outs:
    - models/model.joblib
  
  log_production_model:
    cmd: python src/log_production_model.py --config=params.yaml
    deps:
      - src/log_production_model.py


